Added refuse-root in bin/server

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -6,11 +6,11 @@
 ################################################################################
 
 # refuse root
-#if [ "x${UID}" = "x0" ] || [ "x$(whoami)" = "xroot" ]
-#then
-#    echo "You cannot use the server as root!"
-#    exit 1
-#fi
+if [ "x${UID}" = "x0" ] || [ "x$(whoami)" = "xroot" ]
+then
+    echo "You cannot use the server as root!"
+    exit 1
+fi
 
 ################################################################################
 
